# ios/Podfile

platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  # Ensure Flutter is set up correctly
  flutter_root = File.expand_path(File.join('..', 'flutter'))
  unless File.exist?(flutter_root)
    flutter_root = ENV['FLUTTER_ROOT']
  end
  raise "Could not find Flutter root" unless flutter_root
end

# You can remove the above method if you don't use custom Flutter setup

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(_FILE_))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end