class CategoryConstants {
  static const String footwear = 'Footwear';
  static const String fashion = 'Fashion';
  static const String mobile = 'Mobile';
  static const String electronics = 'Electronics';
  static const String accessories = 'Accessories';
  static const String home = 'Home';
  static const String furniture = 'Furniture';
  static const String beauty = 'Beauty';
  static const String books = 'Books';
  static const String toys = 'Toys';
  static const String laptop = 'Laptop';
  static const String headphone = 'HeadPhone';
  static const String personalCare = "Personal Care";
  static const String stationary = "Stationary";
  static const String groceries = "Groceries";
  static const String cosmetics = "Cosmetics";
  static const String photoFrame = "Photo Frame";

  //just for safety purpose
  static const List<String> clothingKeywords = [
    "Fashion",
    "Fashion",
    "Bottom Wear",
    "clothing",
    "dress",
    "Mens",
    "shirt",
    "shirts",
    "tshirt",
    "tshirts",
    "kurti",
    "tops",
    "blouse",
    "frock",
    "gown",
    "lehenga",
    "skirt",
    "trousers",
    "jeans",
    "pants",
    "shorts",
    "sweater",
    "hoodie",
    "jacket",
    "coat",
    "blazer",
    "cardigan",
    "saree",
    "salwar",
    "ethnic wear",
    "casual wear",
    "formal wear",
    "party wear",
    "nightdress",
    "jumper",
    "hooded jacket",
    "windbreaker",
    "tracksuit",
    "activewear",
    "yoga pants",
    "leggings",
    "sport shorts",
    "polo shirt",
    "men shirt",
    "men tshirt",
    "women shirt",
    "women dress",
    "fashion top",
    "blazer jacket",
    "evening gown",
    "cocktail dress",
    "maxi dress",
    "mini dress",
    "shirt dress",
    "summer dress",
    "winter dress",
    "party dress",
    "workout top",
    "crop top",
    "tank top",
    "long sleeve shirt",
    "short sleeve shirt",
    "tunic",
    "kaftan",
    "peplum top",
    "kimono",
    "bodysuit",
    "pajama set",
    "nightwear",
    "lingerie",
    "underwear",
    "sports bra",
    "swimwear",
    "bikini",
    "trousers suit",
    "linen shirt",
    "denim jacket",
    "leather jacket",
    "jean jacket",
    "corduroy pants",
    "culottes",
    "sweatshirt",
    "hoodie jacket",
    "poncho",
    "cape",
    "gilet",
    "waistcoat",
    "vest",
    "shirt jacket",
    "kimono jacket",
    "sarong",
    "sling dress",
    "robe",
    "athletic shirt",
    "sports shorts",
    "athletic leggings",
    "active leggings",
    "cycling shorts",
    "boardshorts",
    "hooded sweatshirt",
    "cardigan sweater",
    "turtle neck",
    "cashmere sweater",
    "v-neck sweater",
    "crew neck sweater",
    "slip dress",
    "maxi skirt",
    "mini skirt",
    "pencil skirt",
    "pleated skirt",
    "skater skirt",
    "wrap dress",
    "jumpsuit",
    "romper",
    "boho dress",
    "blouse dress",
    "halter top",
    "halter neck dress",
    "sundress",
    "peasant dress",
    "ankle boots",
    "high heel boots",
    "combat boots",
    "Chelsea boots",
    "cowboy boots",
    "over-the-knee boots",
    "platform shoes",
    "moccasins",
    "loafers",
    "sneakers",
    "slip-on shoes",
    "flip flops",
    "wedge sandals",
    "heels",
    "pumps",
    "stiletto heels",
    "flats",
    "espadrilles",
    "ballet flats",
    "sandals",
    "boots",
    "knee-high boots",
    "faux fur coat",
    "parka",
    "trench coat",
    "raincoat",
    "puffer jacket",
    "bomber jacket",
    "vintage jacket",
    "double-breasted coat",
    "pea coat",
    "quilted jacket",
    "fur vest",
    "padded jacket",
    "polar fleece",
    "fleece jacket",
    "softshell jacket",
    "suit jacket",
    "blazer dress",
    "sequin dress",
    "bodycon dress",
    "pencil dress",
    "A-line dress",
    "floral dress",
    "chiffon dress",
    "lace dress",
    "sequined dress",
    "knit dress",
    "sheath dress",
    "wrap skirt",
    "short skirt",
    "high-waisted skirt",
    "long skirt",
    "harem pants",
    "palazzo pants",
    "bootcut jeans",
    "skinny jeans",
    "wide-leg pants",
    "slacks",
    "paperbag waist pants",
    "cargo pants",
    "joggers",
    "sweatpants",
    "chinos",
    "linen pants",
    "flared pants",
    "bell-bottoms",
    "bell-sleeve top",
    "peplum top",
    "blazer vest",
    "oversized shirt",
    "oversized hoodie",
    "longline coat",
    "faux leather skirt",
    "faux leather pants",
    "velvet dress",
    "satin dress",
    "silk blouse",
    "silk shirt",
    "satin skirt",
    "sequin top",
    "glitter top",
    "sequined skirt",
    "puffer vest",
    "culotte pants",
    "culotte skirt",
    "tailored trousers",
    "asymmetrical dress",
    "geometric dress",
    "animal print dress",
    "tropical dress",
    "abstract print shirt",
    "floral print blouse",
    "tie-dye dress",
    "tie-dye t-shirt",
    "graphic tee",
    "statement tee",
    "printed tee",
    "vintage t-shirt",
    "graphic hoodie",
    "camouflage jacket",
    "denim shirt",
    "denim skirt",
    "denim shorts",
    "cargo shorts",
    "cargo jacket",
    "printed pants",
    "patterned pants",
    "striped top",
    "polka dot dress",
    "plaid shirt",
    "checked shirt",
    "flannel shirt",
    "oxford shirt",
    "linen pants",
    "cropped jeans",
    "straight leg jeans",
    "mom jeans",
    "boyfriend jeans",
    "bootcut jeans",
    "ripped jeans",
    "distressed jeans",
    "patchwork jeans",
    "wide-leg jeans",
    "flared jeans",
    "high-waisted jeans",
    "low-rise jeans",
    "stretch jeans",
    "denim overalls",
    "overall dress",
    "overalls",
    "graphic leggings",
    "mesh leggings",
    "legging skirt",
    "leggings with pockets",
    "active tank top",
    "yoga top",
    "workout hoodie",
    "running shorts",
    "gym shorts",
    "exercise leggings",
    "compression tights",
    "compression shorts",
    "cycling leggings",
    "swimming trunks",
    "swim trunks",
    "swim shorts",
    "bathing suit",
    "one-piece swimsuit",
    "two-piece swimsuit",
    "bikini top",
    "bikini bottom",
    "swim briefs",
    "speedo",
    "board shorts",
    "surf shorts",
    "wet suit",
    "diving suit",
    "diving shorts",
    "swim cap",
    "swim goggles",
    "beach towel",
    "sun hat",
    "sunglasses",
    "sunscreen",
    "beach bag",
    "sun dress",
    "flip-flops",
    "fleece pants",
    "thermal pants",
    "thermal shirt",
    "thermal socks",
    "thermal wear",
    "winter gloves",
    "wool scarf",
    "cashmere gloves",
    "fleece gloves",
    "trench dress",
    "pinafore",
    "lace top",
    "sweater dress",
    "bandage dress",
    "knitted dress",
    "cut-out dress",
    "velvet jacket",
    "faux fur vest",
    "fur-lined boots",
    "fur coat",
    "plush robe",
    "feather jacket",
    "leopard print jacket",
    "zip-up hoodie",
    "button-down shirt",
    "embroidered dress",
    "embroidered top",
    "beaded dress",
    "beaded top",
    "lace-up boots",
    "cropped jacket",
    "chiffon blouse",
    "ruffle top",
    "smock dress",
    "puffer pants",
    "suede boots",
    "trench vest",
    "oversized blazer",
    "oversized coat",
    "faux fur jacket",
    "zipped jacket",
    "zippered hoodie",
    "bomber vest",
    "military jacket",
    "patchwork jacket",
    "utility jacket",
    "striped pants",
    "floral leggings",
    "camouflage pants",
    "graphic pants",
    "geometric pants",
    "boho blouse",
    "boho top",
    "boho dress",
    "vintage jacket",
    "vintage dress",
    "tartan skirt",
    "tartan pants",
    "monochrome dress",
    "monochrome top",
    "metallic dress",
    "metallic top",
    "sequined top",
    "flared blouse",
    "ruffle skirt",
    "lace dress",
    "mesh dress",
    "sheer dress",
    "silk skirt",
    "midi skirt",
    "tropical print dress",
    "plaid pants",
    "checkered pants",
    "herringbone dress",
    "herringbone skirt",
    "gingham dress",
    "gingham skirt",
    "leopard print dress",
    "zebra print dress",
    "snake print skirt",
    "floral print blouse",
    "camisole",
    "sports shorts",
    "sport leggings",
    "elastic waist pants",
    "flannel pants",
    "crochet dress",
    "crochet top",
    "knit skirt",
    "knit top",
    "knit pants",
    "wrap pants",
    "bodysuit dress",
    "two-tone dress",
    "color-block dress",
    "color-block top",
    "kimono top",
    "knee-length skirt",
    "fit-and-flare dress",
    "A-line skirt",
    "high-low skirt",
    "flare dress",
    "fitted blouse",
    "fitted pants",
    "skirt suit",
    "vest top",
    "racerback top",
    "romper dress",
    "mesh top",
    "mesh skirt",
    "bubble skirt",
    "bell-bottom pants",
    "faux leather pants",
    "peacoat",
    "utility pants",
    "peplum blouse",
    "strapless dress",
    "strapless top",
    "seamless leggings",
    "sheer blouse",
    "high-waisted shorts",
    "high-waisted jeans",
    "bootcut pants",
    "drawstring pants",
    "bandeau top",
    "lace skirt",
    "bohemian dress",
    "bohemian top",
    "swing dress",
    "wrap blouse",
    "turtle neck top",
    "v-neck dress",
    "square neck dress",
    "halter top",
    "muscle tank",
    "polo dress",
    "blazer dress",
    "sleek dress",
    "shift dress",
    "shift blouse",
    "batwing top",
    "oversized sweater",
    "oversized t-shirt",
    "sweater vest",
    "asymmetrical top",
    "shirt dress",
    "pleated blouse",
    "bandana top",
    "bucket hat",
    "sports jersey",
    "jumper dress",
    "sweater skirt",
    "spaghetti strap top",
    "lace bralette",
    "crochet bralette",
    "sports jacket",
    "windbreaker pants",
    "athletic shorts",
    "chino shorts",
    "cargo vest",
    "jogger pants",
    "cargo jacket",
    "double breasted jacket",
    "rain jacket",
    "performance jacket",
    "windbreaker jacket",
    "snow boots",
    "snow pants",
    "ski pants",
    "ski jacket",
    "fleece vest",
    "sherpa jacket",
    "shacket",
    "puffer coat",
    "sheepskin coat",
    "parka coat",
    "puffer vest",
    "wool coat",
    "thermal jacket",
    "fur-lined boots",
    "golf polo",
    "chino pants",
    "beach cover-up",
    "denim overalls",
    "lounge pants",
    "fleece hoodie",
    "beach hat",
    "sweatband",
    "fanny pack",
    "cargo shorts",
    "cargo pants",
    "brimmed hat",
    "baseball cap",
    "snapback",
    "beanie hat",
    "bucket hat",
    "summer hat",
    "cardigan coat",
    "cable knit sweater",
    "zip hoodie",
  ];

  static List<String> mobileKeywords = [
    "mobile",
    "mobiles",
    "phone",
    "phones",
    "smartphone",
    "smartphones",
    "android phone",
    "android phones",
    "iPhone",
    "iPhones",
    "cell phone",
    "cell phones",
    "mobile phone",
    "mobile phones",
    "mobile device",
    "mobile devices",
    "smart mobile",
    "touch phone",
    "4G phone",
    "5G phone",
    "dual sim phone",
    "flagship phone",
    "cheap mobiles",
    "budget smartphones",
    "latest smartphones",
    "new mobile phone",
    "mobile handset",
    "mobile gadget",
    "mobile technology",
    "mobile communication",
    "mobile electronics",
    "wireless phone",
    "touchscreen phone",
    "camera phone",
    "gaming phone",
    "business phone",
    "smart device",
  ];
  static List<String> laptopKeywords = [
    "laptop",
    "laptops",
    "notebook",
    "notebooks",
    "gaming laptop",
    "ultrabook",
    "macbook",
    "windows laptop",
    "chromebook",
  ];

  static List<String> electronicsKeywords = [
    "electronics",
    "electronic device",
    "gadgets",
    "home electronics",
    "consumer electronics",
    "smart electronics",
  ];

  static List<String> accessoriesKeywords = [
    "accessories",
    "mobile accessories",
    "laptop accessories",
    "computer accessories",
    "tech accessories",
    "phone case",
    "charger",
    "earphones",
    "headphones",
    "smartwatch",
  ];

  static List<String> homeKeywords = [
    "home",
    "home essentials",
    "home products",
    "home decor",
    "home improvement",
    "kitchen items",
    "home storage",
  ];

  static List<String> furnitureKeywords = [
    "furniture",
    "home furniture",
    "wooden furniture",
    "office furniture",
    "sofa",
    "table",
    "chair",
    "bed",
    "wardrobe",
  ];

  static List<String> beautyKeywords = [
    "beauty",
    "beauty products",
    "makeup",
    "skincare",
    "haircare",
    "beauty essentials",
  ];

  static List<String> bookKeywords = [
    "books",
    "novels",
    "fiction books",
    "non-fiction books",
    "children books",
    "educational books",
    "textbooks",
  ];

  static List<String> toyKeywords = [
    "toys",
    "kids toys",
    "educational toys",
    "baby toys",
    "action figures",
    "dolls",
    "puzzles",
  ];

  static List<String> personalCareKeywords = [
    "personal care",
    "body care",
    "hair care",
    "oral care",
    "skin care",
    "men grooming",
    "women grooming",
  ];

  static List<String> stationeryKeywords = [
    "stationery",
    "office supplies",
    "notebooks",
    "pens",
    "diaries",
    "folders",
    "writing materials",
  ];

  static List<String> groceryKeywords = [
    "grocery",
    "daily needs",
    "food items",
    "vegetables",
    "fruits",
    "snacks",
    "beverages",
  ];

  static List<String> cosmeticsKeywords = [
    "cosmetics",
    "makeup products",
    "lipstick",
    "foundation",
    "eyeliner",
    "blush",
    "nail polish",
  ];

  static List<String> photoFrameKeywords = [
    "photo frame",
    "picture frame",
    "wall frame",
    "tabletop frame",
    "decorative frame",
    "wooden frame",
  ];
  static List<String> jewelleryKeywords = [
    "jewellery",
    "jewelry",
    "fashion jewellery",
    "imitation jewellery",
    "designer jewellery",
    "traditional jewellery",
    "handmade jewellery",
    "bridal jewellery",
    "wedding jewellery",
    "ethnic jewellery",

    "necklace",
    "necklaces",
    "ring",
    "rings",
    "earrings",
    "earring",
    "bracelet",
    "bracelets",
    "bangle",
    "bangles",
    "anklet",
    "anklets",
    "toe ring",
    "toe rings",
    "nose ring",
    "nose pin",
    "mangalsutra",
    "choker",
    "pendant",
    "pendants",
    "brooch",
    "jewellery set",
    "jewellery combo",

    "gold jewellery",
    "silver jewellery",
    "diamond jewellery",
    "platinum jewellery",
    "artificial jewellery",
    "pearl jewellery",
    "kundan jewellery",
    "polki jewellery",
    "oxidised jewellery",
    "temple jewellery",
    "stone jewellery",
    "gemstone jewellery",
    "beaded jewellery",

    "party wear jewellery",
    "daily wear jewellery",
    "office wear jewellery",
    "festival jewellery",
    "gift jewellery",
  ];
  static List<String> footwearKeywords = [
    "footwear",
    "shoes",
    "shoe",
    "slippers",
    "sandals",
    "flip flops",
    "boots",
    "loafers",
    "sneakers",
    "sports shoes",
    "formal shoes",
    "casual shoes",
    "walking shoes",
    "running shoes",
    "ethnic footwear",
    "party wear shoes",
    "daily wear footwear",
    "branded shoes",
    "designer shoes",

    "men shoes",
    "women shoes",
    "kids shoes",
    "boys footwear",
    "girls footwear",
    "ladies sandals",
    "men slippers",
    "women slippers",
    "children sandals",

    "high heels",
    "pumps",
    "ballerina shoes",
    "mules",
    "platform shoes",
    "wedges",
    "ankle boots",
    "combat boots",
    "oxfords",
    "derby shoes",
    "chappals",
    "mojari",
    "juttis",
    "kolhapuri chappals",

    "leather shoes",
    "canvas shoes",
    "rubber slippers",
    "mesh shoes",
    "synthetic footwear",
    "suede shoes",

    "gym shoes",
    "hiking boots",
    "trekking shoes",
    "football shoes",
    "cricket shoes",
    "tennis shoes",

    "rainy shoes",
    "winter boots",
    "summer slippers",
  ];
}
